### PR TITLE
Update macos-build-script.sh

### PR DESCRIPTION
**Pull request by hyrulelinks**
- Change realesrgan-ncnn-vulkan to upscayl-ncnn, the latter is a continued development project of the former
- The script will auto download the latest executable program of upsample-ncnn and the model of realsr-ncnn-vulkan from the project release. realesrgan-ncnn-vulkan is still the outdated Sep 2022 version that has not been maintained for a long time
- Add RealSR model to provide higher super-resolution fidelity for real photos
- Eliminate the 2x and 3x versions of Real-ESRGAN's animevideov3 due to their inadequate upscaling capabilities and tendency to generate flawed images
- Modify the script content for downloading the Super Resolution executable program and models
- The script has been tested successfully on the M1 Max Macbook Pro
@TransparentLC

### CODE REVIEW

**Comment by TransparentLC** [comment]
I hadn't realized that Real-ESRGAN still has actively maintained forks, thanks!

I still need some time to update the readme and other CI builds, and then I will merge it.

**Comment by hyrulelinks** [comment]
The arm64 macOS-13-xlarge runner requires payment to use. Multiple attempts to set up an arm64 build environment on the x86_64 macOS-13 runner have failed. Therefore, for Apple users with M-chip, the quickest and most feasible option is to remotely script and package locally.

**Comment by hyrulelinks** [comment]
Removed the renaming section, please review
@TransparentLC

**Comment by TransparentLC** [comment]
And the choice of using mirror site or not ...

**Pull request merged**
