### PR TITLE
Added a simple progressbar to very bottom of the app.

### PR DESCRIPTION
**Pull request by NandeMD**
With no progress:

p1

With about a quarter done:

p2

### CODE REVIEW

**Comment by TransparentLC** [comment]
I used to consider adding a progress bar by simply dividing the length of the queue with the counter as your implementation does but soon gave up.

One reason is that the length of the queue is not fixed during processing. The `SplitGIFTask` will append `RESpawnTask` to the queue for each frame in the GIF. Furthermore, the execution time of each task differs. `RESpawnTask` would take a lot of time, other tasks can be done instantly, but they will have the same length on the progress bar under the simple division.

Even so, I still think adding a determinate progress bar is a good idea. However, I think its length could be determined by the number of files (not tasks) to be processed, and also the `(\d+[,.]\d+)%` can be parsed from each line of `RESpawnTask`'s output so the progress can be shown more accurately. I will accept the pull request if this can be achieved.

Anyway, thanks for your contribution!

**Comment by NandeMD** [comment]
Thanks for your feedback! I will try to come up with some solution this weekend.

**Comment by NandeMD** [comment]
I'm putting this pull request on hold since I couldn't find a satisfactory solution. If an alternative solution comes to mind, I will work on it again.

**Comment by TransparentLC** [comment]
https://github.com/TransparentLC/realesrgan-gui/assets/47057319/c6606570-8b55-4e1d-a848-3cf5202042e4

I tried to implement the progress bar by myself. In my design, the length of the progress bar is calculated from three variables:

* `a` Current file's progress, a float from 0 to 1.
* `b` Number of files processed
* `c` Number of all files requiring processing

So the length is `(a + b) / c` and only `RESpawnTask` and `SplitGIFTask` will change these variables.

In `RESpawnTask`, the percentage in the output will be parsed to `a`. If a file needs to run Real-ESRGAN multiple times, for example, "1x -> 2x -> 4x", then `a` will be 0\~0.5 during "1x -> 2x" and 0.5\~1 during "2x -> 4x". Finally `a` will be set to 0 and `b` will increase by 1.

In `SplitGIFTask`, if the GIF file has x frames, then `c` will increase by x-1. Of course, the progress bar will roll back😂

Feel free to try it and let me know if there are any problems!

**Comment by NandeMD** [comment]
It's working great. When I tested it on the image sets I regularly use (usually consisting of 100-200 JPEG files with a width of 690 pixels), I didn't encounter any issues. Really perfect!

**Comment by TransparentLC** [comment]
https://github.com/TransparentLC/realesrgan-gui/assets/47057319/773bc792-f804-4bdb-a405-37e39d437624

What about an easing animation?

Unfortunately, the animation is not smooth and sometimes jitters as the delay of tkinter's `after` is not accurate. There is nothing equivalent to JavaScript's `requestAnimationFrame` in tkinter.

**Comment by NandeMD** [comment]
Sorry or the late response.

At least while processing my own test images and 2 different GIFs, I didn't observe any jitter on my 144 Hz monitor, but I noticed very little when processing a low FPS GIF on my 60 Hz monitor. I guess jitter is more noticable with low quality, fast processing and low quantity files/folders (when processes end fast) because i didn't notice  I tried to add `self.master.update()`, `self.update()` and `self.progressbar.update()` after `self.vardoubleProgress.set(...)` in `writeToOutput()` method but i didn't see any improvements. Maybe we can add some linear interpolation before calling `progressbar.set()` but i am afraid that will reduce the responsiveness of the progressbar.

**Comment by TransparentLC** [comment]
I have already used an [`easeOutCubic`](https://easings.net/#easeOutCubic) interpolation.

https://github.com/TransparentLC/realesrgan-gui/blob/07ee4d8a4cc42eaab9fc07109782565249e284c3/main.py#L529

I use `after_cancel` to cancel the previous animation and set a new one when the progress changes. However, I noticed that the animation (or the scheduled ID) canceled by `after_cancel` is still executed when there is a jitter.

Added some additional checks and I haven't encountered any jitter yet.

**Pull request closed without merging**
