### PR TITLE
Added Language Selection in GUI

### PR DESCRIPTION
**Pull request by NandeMD**
Added a language selector combobox in Advanced frame. With this, user can change app text to any language defined in `i18n.ini` with just a simple combobox selection. Selected language will be saved in `config.ini` and used in next startup.

- Language change is immediate so users and translators can experiment with the text. 
- Language list is automatically generated so anyone can add any language with a simple `i18n.ini` update and restart the app.
- Language dropdown is a list of language display names (native) generated from local codes in `i18n.ini`.

Note: I tried not to change default behaviour of the original app while adding this feature.

### CODE REVIEW

**Comment by TransparentLC** [comment]
Pretty useful feature!

Is it possible to not import babel in the code? It comes with about 30 MB of locale data, however this program is only about 10 MB when packaged with Pyinstaller (on Windows).

I think the `locales_map` can be modified like this:

```py
# Map all locale display names to locale codes
# Get display names with babel, but don't import it because of its huge size
# from babel import Locale
# Locale.parse('zh_CN').get_display_name()
locales_map = {
    '中文 (简体, 中国)': 'zh_CN',
    'English (United States)': 'en_US',
    ...,
}
```

**Comment by NandeMD** [comment]
Okay, i will update the pr when it get home. I didn't realise the huge local data.

**Comment by NandeMD** [comment]
Finally i'm free. I will update i18n.py and in the main directory i will add a simple script to generate locales_map for translators, then i will update README.tr-TR.md and README.en-US.md.

**Comment by NandeMD** [comment]
@TransparentLC Now it should be OK to merge.

**Pull request merged**
